### ISSUE TITLE
upgrade std_data_json to 0.18.1

### ISSUE THREAD

**Issue by yannick** [forbjok/jsonserialized#2]
please quickly bump the version and deploy

**Comment by forbjok** [comment]
I just looked into this, and there appears to be a bug in v0.18.1 (or specifically, most likely the version of taggedalgebraic used by that version) that causes it to throw an AssertError when trying to convert integer JSONValues to int.

I've reported the issue. https://github.com/s-ludwig/std_data_json/issues/22
Once this is solved, I'll look into upgrading again.

**Comment by yannick** [comment]
hmm, could this not be worked around by just doing cast(int) ?

**Comment by yannick** [comment]
Fix is in taggedalgebraic 0.10.2: s-ludwig/taggedalgebraic@a0415ed

**Comment by forbjok** [comment]
I've updated std_data_json to v0.18.2 as well as some other fixes.
It should now be working with at least DMD v2.071.1 and LDC v1.1.0-beta5.
